Feature/compare image
kiku-h/latteart-repository pull request #9
Opened 2022-10-17 06:16 UTC by mamoru-x-yanagisawa

2022-10-17 06:37 UTC, fujiwr requested changes

2022-10-17 06:37 UTC, fujiwr commented on src/index.ts
> +      UpdateTestStepsEntity1664956770085,
単数形でお願いします。

2022-10-17 06:37 UTC, fujiwr commented on src/lib/compareImage.ts
> +export default class CompareImage {
名詞(`PNGImageComparison`等)でお願いします。

2022-10-17 06:37 UTC, fujiwr commented on src/services/TestStepService.ts
> +    if (
PNG以外が来た場合は単にスキップするだけでなく、警告をフロント側に通知するようにしたほうが良いと思います。

2022-10-19 04:42 UTC, mamoru-x-yanagisawa commented on src/index.ts
> +      UpdateTestStepsEntity1664956770085,
単数形に修正しました

2022-10-19 04:42 UTC, mamoru-x-yanagisawa commented on src/lib/compareImage.ts
> +export default class CompareImage {
ご指摘の通り修正致しました

2022-10-19 04:44 UTC, mamoru-x-yanagisawa commented on src/services/TestStepService.ts
> +    if (
ご指摘の通り修正しました。返すパラメータを一つ追加しました。（`hasSkipImageCompare`）

2022-10-19 08:46 UTC, fujiwr requested changes

2022-10-19 08:46 UTC, fujiwr commented on src/services/TestResultService.ts
> +      hasSkipImageCompare,
`hasInvalidScreenshots`はいかがでしょうか。

2022-10-19 09:01 UTC, mamoru-x-yanagisawa commented on src/services/TestResultService.ts
> +      hasSkipImageCompare,
ご指摘の通り修正いたしました

2022-10-19 09:28 UTC, fujiwr approved these changes

2022-10-19 09:28 UTC, merged